### ISSUE TITLE
'a2enmod version' in installation instructions

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/doc-otobo-installation#1]
I installed OTOBO under Ubuntu 19.10. One of the suggested commands in the installation guide is a2enmod version This command failed with the message:

    ERROR: Module version does not exist!

https://stackoverflow.com/questions/38568364/module-version-in-apache and https://forum.otterhub.org/viewtopic.php?p=161271 told me that the Apache2 module is already compiled in. Therefore I propose to simply remove this instruction.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

perfekt, thanks very much for your help!

Stefan
