### ISSUE TITLE
Invalid link to Docker Hub

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/doc-otobo-installation#107]
@StefanAbel-OTOBO reported a broken link:  

> Docker compose can be used for fetching the wanted images from https://hub.docker.com/repository/docker/rotheross/.

**Comment by bschmalhofer** [comment]
@StefanAbel-OTOBO  Could you check tomorrow, after the nightly build, whether the links are working now?

**Comment by StefanAbel-OTOBO** [comment]
> @StefanAbel-OTOBO Could you check tomorrow, after the nightly build, whether the links are working now?

Bernhard, I checked in the "Updating a Docker-based Installation of OTOBO" manual and it seems my pull request didn't work. The link(s) still do(es)n't work.

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO : Could you check whether the nightly build of https://doc.otobo.org/manual/installation/10.1/en/content/updating-docker.html is working? In git the file looks fine, https://github.com/RotherOSS/doc-otobo-installation/blob/master/content/updating-docker.rst.
This might also be the reason why the "Edit on Github" in the upper right still does not work.

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO 
Look like the automatic update of https://doc.otobo.org/manual/installation/10.1/en/content/updating-docker.html is not working. At least I did not see the changes made in https://github.com/RotherOSS/doc-otobo-installation/commit/69c3c6ec6b09b8fa9f0438c0309c97ad3f1157c0 .

**Comment by bschmalhofer** [comment]
The links in https://doc.otobo.org/manual/installation/10.1/en/content/updating-docker.html look fine now. Closing this issue.
