### ISSUE TITLE
Document the possibility to use sshfs or mounts for migration

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/doc-otobo-installation#12]
Security conscious users should be wary of giving their SSH password to a web application. IMHO it should be clarified that for migration only a read only access to the OTRS 6 home dir is needed. This read only access can be achieved either with mounting a remote file system or by using sshfs. Alternatively the remote file system could be copied, preferentially with rsync, to the migration server.

**Comment by wornet-aer** [comment]
From my point of view this is somehow out of scope of the OTOBO documentation. I think a short hint should be enough, as I'd expect all sysadmins to be able to use such basic linux file copy/mount techniques. Especially those ones, who are very security conscious. And if they are not familiar with it yet, I think it is ok to assume that they will be able to search for an `rsync` or `sshfs` documentation theirselves.

**Comment by bschmalhofer** [comment]
Yes, trying to document all possible scenarios is a futile task. Thus I simply added an optional step, stating that mounting _/opt/otrs_ is a viable option. I'm hesitant to label it as the recommended option, as I don't have experience with actual customer migrations.
Closing this issue, as using a mount is now mentioned as an option.
