### ISSUE TITLE
Docker Backup and Restore double + issue

### ISSUE THREAD

**Issue by nm583** [RotherOSS/doc-otobo-installation#120]
1. The part with docker-based backup and restore is doubled in the documentation.
https://doc.otobo.org/manual/installation/10.1/de/content/backup-restore.html#considerations-for-running-otobo-under-docker
https://doc.otobo.org/manual/installation/10.1/de/content/backup-restore-docker.html
Contents differ slightly. The second one seems to have more information, but I'm not sure which is better and since I'm very new to Otobo and Docker I didn't want to mess it up by editing it myself.

2. `docker run` has `rotheross/otobo:latest-10_0`, but the guide is for 10.1. Shouldn't it match?

3. The last one is more kind of a question: `docker volume create` uses `$PWD/otobo_backup` and `docker run` uses `/otobo_backup`.
Is that correct?

**Comment by bschmalhofer** [comment]
Hi @nm583,

this answer is very late, sorry for that.

re 1: I confirm that the documentation is still duplicated. This must be fixed.

re 2: It should match. I have updated the document in the git repository

re 3: I think that this is correct. On the Docker host the backup directory is in _$PWD/otobo_backup_. But the scripts runs within a container where that directory is mounted in the path _/otobo_backup_.

**Comment by nm583** [comment]
Hi,

No problem.
And since my "issue" was just me not understanding something properly, it's alright.
Thanks for explaining!

**Comment by bschmalhofer** [comment]
Removed the duplicated content. Closing this issue now.
