### ISSUE TITLE
Suggestion to change sentence referencing to 10.0.8 in docker installation page

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/doc-otobo-installation#125]

**Comment by bschmalhofer** [comment]
I don't know whether this fits in here. In https://doc.otobo.de/manual/installation/11.0/en/content/updating-docker.html the release 11.0.7 is used as an example. This is a bit confusing as there is no 11.0.7 yet.

**Comment by stefanhaerter** [comment]
To be honest, I'm a bit confused by your reply - what would be your suggestion or what would you recommend to do?

**Comment by bschmalhofer** [comment]
I was suggesting to use 11.0.1 as an example version. But just because I was confused about the 11.0.7.

```
~/devel/OTOBO/doc-otobo-installation$ grep -r 11.0.7 content/
content/updating-docker.rst:    Please substitute it with the real version, e.g. **11.0.7**.
```

**Comment by stefanhaerter** [comment]
I just updated the version strings accordingly.

**Comment by bschmalhofer** [comment]
I have updated the section where 10.0.8 is mentioned in rel-10_0, rel-10_1, and rel-11_0. There is no need to mention the availability since 10.0.8 in rel-10_1 and rel-11_0.

Closing this issue.
