### ISSUE TITLE
Prefer sites-available for zzz_otobo.conf

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/doc-otobo-installation#20]
In [Configure Apache without SSL support](https://doc.otobo.org/manual/installation/stable/en/content/installation.html#configure-apache-without-ssl-support)

```
root> cp /opt/otobo/scripts/apache2-httpd.include.conf /etc/apache2/sites-enabled/zzz_otobo.conf
root> systemctl restart apache2
```

copying directly to `sites-enabled` is against convenient administration in case of shared hosting or multiple services (e.g. webmail, monitoring). It can have surprising side-effects.

Also the file would be better named 

```
/etc/apache2/sites-available/zzz_otobo-80.include.conf
```

or just

```
/etc/apache2/sites-available/otobo-http.include.conf
```

`systemctl restart apache2` should enough instead of `restart`.

Just a reminder.

**Comment by bschmalhofer** [comment]
@wollmers   I second that we should do away with the _zzz_otobo.conf_ file. My hunch is that it isn't really necessary. During the installation we could copy or link all the sample .conf file into _sites-available_. Choosing the relevant file could then be done with ``a2enmod``.

**Comment by wollmers** [comment]
@bschmalhofer There a PROs and CONs. Webserver admins have their own preferences. I would only copy otobo.include.conf and and otobo.http.apache-sample.conf (rename to www.mydomain.com.conf) to sites-available, `a2ensite` or `ln -s`into sites enabeled. Then certbot works automagically (create, verify and renew certificates). Or `cp -a www.mydomain.com.conf www.mydomain.com.ssl.conf` and add the certificate paths.

If you want to use different web-apps on the same (or more than one) sub-domain e. g.

```
http://www.mydomain.com/otobo/
http://www.mydomain.com/wordpress/
http://www.mydomain.com/webmail/
http://www.mydomain.com/db-viewer/
```

then theoretically `/etc/apache2/conf.d/otobo.conf` could be used, but don't try it. Been there, done that and wasted time.

**Comment by bschmalhofer** [comment]
Copying files into sites-enabled is really ugly. So for the scope of this issue:

- [ ] keep the traditional name zzz_otobo.conf
- [ ] document that it should be copied into sites-available
- [ ] enable OTOBO with `a2ensite zzz_otobo`

**Comment by bschmalhofer** [comment]
PR is merged. Closing this issue, being confident that https://doc.otobo.org/manual/installation/stable/en/content/installation.html will be updated automatically.
