### ISSUE TITLE
mention how to check for SELinux

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/doc-otobo-installation#3]
When installing OTOBO on Ubuntu 19.10 I wasn't sure whether SELinux was enabled. I think that it is worthwhile to mention the command 'sestatus'. This commands checks whether SELiniux is active.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

I add a short description about sestatus to the tutorial.
Thanks very much for your help!

Stefan
