### ISSUE TITLE
otobo.CheckEnvironment.pl is missing

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/doc-otobo-installation#4]
In https://doc.otobo.org/manual/installation/stable/en/content/requirements.html the command `otobo.CheckEnvironment.pl ` is mentionend. However this command does not exist in OTOBO. I assume that otobo.CheckModules.pl is meant.

**Comment by bschmalhofer** [comment]
I created a pull request for this issue. In that PR I left locale/content.pot unchanged, as it looks like a generated file.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

perfekt, thanks very much for your help!

Stefan
