### ISSUE TITLE
Document required database Versions

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/doc-otobo-installation#40]
I did not find the minimally required versions for MySQL, MariaDB, PostgreSQL and Oracle. If these versions are documented somewhere, then they probably should be presented more prominently in the installation manual.
Requiring MySQL 5.7.7 would have the advantage that the index key length of 767 bytes no longer applies.

**Comment by StefanRother-OTOBO** [comment]
Hi Bernhard,

the required database version is present prominently enough I think?
https://doc.otobo.org/manual/installation/stable/en/content/requirements.html#software-requirements

A more detailed definition was not needed until now.

Best wishes,

Stefan

**Comment by bschmalhofer** [comment]
Yes. Closing the issue.
