### ISSUE TITLE
"Edit on Github" is broken

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/doc-otobo-installation#51]
The generated docs are available at https://doc.otobo.org/manual/installation/stable/en/content/installation-docker.html . It has an "Edit on Github" link that points to https://github.com/OTOBO/doc-installation/. However that link is broken. 
I suppose that the link should be https://github.com/RotherOSS/doc-otobo-installation.

**Comment by bschmalhofer** [comment]
Looks like otobo-bot broke conf.py again, the day after @wollmers  fixed it. See the commit 570e4f957c60963a9b176272d1520ef6bca07aaf . So, it looks like otobo-bot needs to be updated.

@StefanRother-OTOBO  or @svenoe : Could you do that?

**Comment by bschmalhofer** [comment]
@StefanRother-OTOBO "Edit on GitHub" is still not working.

**Comment by StefanRother-OTOBO** [comment]
Fixed!
