### ISSUE TITLE
otobo-bot changes corrections back

### ISSUE THREAD

**Issue by wollmers** [RotherOSS/doc-otobo-installation#54]
See https://github.com/RotherOSS/doc-otobo-installation/commit/570e4f957c60963a9b176272d1520ef6bca07aaf

**Comment by bschmalhofer** [comment]
Still the same problem. See 351a6b18fe5b51605be8e6fff07371e2dc8144e9

**Comment by bschmalhofer** [comment]
This seems to be fixed now.
