### ISSUE TITLE
otobo_web_1 and otobo_daemon_1 no longer run as root

### ISSUE THREAD

**Issue by christian1980nrw** [RotherOSS/doc-otobo-installation#65]
Hello i read at https://github.com/RotherOSS/otobo-docker/issues/26 that you changed otobo_web_1 and otobo_daemon_1 so that they no longer run as root. 

Can you explain or extend your howto-documents to get higher rights now for maintenance?
If i login to the container with sudo docker exec -it --user root otobo_web_1 bash
i am not able to use su anymore.

su: cannot set groups: Operation not permitted

Thanks. Christian

**Comment by bschmalhofer** [comment]
Hi Christian, @christian1980nrw ,

sorry, this took a long time until I got around to look at this issue. 
It looks like a running container can be modified and then be committed as a new image. The trick is to run the container as root and to avoid the default entrypoint script. I have enhanced the installation manual in the pull request #66. Could you also take a look at that section, before we release it as part of the official documentation?

Best regards,
   Bernhard

**Comment by bschmalhofer** [comment]
The updated instructions are now available at https://doc.otobo.org/manual/installation/stable/en/content/installation-docker.html#customizing-the-otobo-docker-image. Closing the issue.

**Comment by humble-b** [comment]
sorry to comment or open this one but the link doesn't work anymore and i was trying to copy file inside Custom folder of the image which i wasn't able to do

run the following:
docker exec -it otobo_web_1 /bin/bash
cd var/httpd/htdocs/skins/
cp Agent/custom/img/logo* Customer/custom/img/ # i have some logo's in this folder from previous install and wanted to use some of them in my Customer location

# Answer:
cp: cannot create regular file Permission denied

**Comment by humble-b** [comment]
never mind. Using mount point /var/lib/docker/volumes/otobo_opt_otobo/_data i was able to do the stuff i needed and this is way better anyway

**Comment by bschmalhofer** [comment]
For some reason the link to 'stable' no longer works. Here is a valid link: https://doc.otobo.org/manual/installation/10.1/en/content/installation-docker.html#customizing-the-otobo-docker-image

**Comment by bschmalhofer** [comment]
@humble-b , yes, using the local directory works equally well. The permission problem you ran into might have been that your _custom/img_ might have been created on the Docker host as the user root. 

Generally creating dirs and copying files within a running container works fine:

> otobo@0dc07ec27315:~/var/httpd/htdocs/skins$ mkdir -p {Agent,Customer}/custom/img
> otobo@0dc07ec27315:~/var/httpd/htdocs/skins$ touch Agent/custom/img/logo_sample.png
> otobo@0dc07ec27315:~/var/httpd/htdocs/skins$ cp Agent/custom/img/logo* Customer/custom/img/
> otobo@0dc07ec27315:~/var/httpd/htdocs/skins$ ls Customer/custom/img/
> logo_sample.png
> otobo@0dc07ec27315:~/var/httpd/htdocs/skins$
